server:
  port: 8080
  # 大模型对话中文乱码问题解决
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  application:
    name: saa-ollama

# springaialibaba config
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:1.7b
